INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '329299', 'Quarkus T-shirt', 11.95, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '329199', 'Quarkus Duffel Bag', 35.45, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '165613', 'Quarkus AirPods',24.15, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '165614', 'Quarkus H2Go water bottle', 14.45, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '165954', 'Quarkus Mug', 12.45, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444434', 'Quarkus Journal Notebook', 13.99, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444435', 'Quarkus Twill Cap', 13.40, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444437', 'Quarkus World Tour T-shirt', 12.75, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444439', 'Quarkus Sticker', 5.75, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444450', 'Quarkus Tumbler', 25.55, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444454', 'Quarkus Picks', 7.25, -1);
INSERT INTO PRODUCT (id, itemId, name, price, quantity) values (nextval('hibernate_sequence'), '444460', 'Quarkus French Black Notebook', 9.99, -1);